# Generated by Django 4.0.1 on 2022-03-13 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travello', '0003_alter_property_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='Cottage villa', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('area', models.IntegerField(max_length=10)),
                ('locality', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=15)),
                ('landseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
