# Generated by Django 4.0.1 on 2022-03-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_property_title_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(),
        ),
    ]
