# Generated by Django 4.0.1 on 2022-03-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='contactno',
            field=models.BigIntegerField(default=9995556457),
        ),
        migrations.AddField(
            model_name='land',
            name='img',
            field=models.ImageField(default='real-estate-ga1b304591_640.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='property',
            name='contactno',
            field=models.BigIntegerField(default=9995556457),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='card',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='incomecertificate',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
