# Generated by Django 4.0.1 on 2022-03-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_land_contactno_land_img_property_contactno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
